apiVersion: v1
kind: Service 
metadata:
  name: {{ .Values.mongodb.service.name }}
  namespace: {{ .Values.service.namespace }}
spec:
  selector:
    app: {{ .Values.service.spec.selector.app }}
  ports:
  - port: {{ .Values.mongodb.spec.containerPort }}
    targetPort: {{ .Values.mongodb.spec.containerPort }}
  type: {{ .Values.mongodb.service.type }}
