apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.Name }}
  namespace: {{ .Values.Namespace }}
spec:
  replicas: {{ .Values.spec.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.deployment.labels.app }}
  template:
    metadata:
      labels:
        app: {{ .Values.deployment.labels.app }}
    spec:
      containers:
      - name: {{ .Values.deployment.container_name }}
        image: "{{ .Values.deployment.image.name }}:{{ .Values.deployment.image.tag }}"
        ports:
        - containerPort: {{ .Values.deployment.containerPort }}
        env:
        - name: {{ .Values.deployment.env.name }}
          valueFrom:
            configMapKeyRef:
              name: {{ .Values.config.name }}
              key: {{ .Values.deployment.env.name }}
