apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secret.name }}
  namespace: {{ .Values.service.namespace }}
type: {{ .Values.secret.type }}
data:
  EMAIL_USER: {{ .Values.secret.data.EMAIL_USER | b64enc }}
  EMAIL_PASS: {{ .Values.secret.data.EMAIL_PASS | b64enc }}
  MONGO_INITDB_ROOT_PASSWORD: {{ .Values.mongodb.password | b64enc }}
