# deployment
apiVersion: apps/v1
kind: Deployment
Name: vegetable-order-app
namespace: dhanush-ns
spec:
  replicas: 3
deployment:
  labels:
    app: vegetable-order-app
  container_name: vegetable-order
  containerPort: 3000
  image: 
    name: dhanushn2003/vegetable-image
    tag: d1.0.1
  env:
    name: MONGO_URL
    value: "mongodb://mongodb-service:27017/vegetableDB"

# service
service: 
  apiVersion: v1 
  kind: Service 
  name: vegetable-service
  namespace: dhanush-ns
  spec:
    selector:
      app: vegetable-order-app
    type: LoadBalancer
    ports:
      port: 80
      targetPort: 3000

# mongodb-depoyment and sevice
mongodb: 
  apiVersion: apps/v1
  kind: Deployment
  name: mongodb-deploy 
  namespace: dhanush-ns
  username: admin
  password: admin123
  spec: 
    replicas: 1
    labels:
      app: mongodb
    container_name: mongodb
    image:
      name: mongo 
      tag: 6
    containerPort: 27017
    env: 
      name: MONGO_INITDB_DATABASE
      username: MONGO_INITDB_ROOT_USERNAME
      config: 
        name: mongodb-config
      key: 
        name: mongodb-secret
        username: MONGO_INITDB_ROOT_PASSWORD
  service: 
    name: mongodb-service 
    type: LoadBalancer

#configmap
config: 
  apiVersion: v1
  kind: ConfigMap
  name: vegetable-order-config
  namespace: dhanush-ns
  secret: "1234"
  database: "mydatabase"

#SECRET
secret:
  name: mongodb-secret
  type: Opaque
  data:
    EMAIL_USER: dhanush@gmail.com
    EMAIL_PASS: dhanush@123
app: 
  port: 3000
