apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.config.name }}
  namespace: {{ .Values.config.namespace }}
data:
  MONGO_URL: {{ .Values.deployment.env.value | quote }}
  SESSION_SECRET: {{ .Values.config.secret | quote }}
  PORT: {{ .Values.app.port | quote }}
  MONGO_INITDB_DATABASE: {{ .Values.config.database | quote }}
  MONGO_INITDB_ROOT_USERNAME: {{ .Values.mongodb.username | quote }}
