apiVersion: {{ .Values.mongodb.apiversion}}
kind: {{ .Values.mongodb.kind }}
metadata:
  name: {{ .Values.mongodb.name}}
  namespace: {{ .Values.mongodb.namespace}}
spec:
  replicas: {{ .Values.mongodb.spec.replicas}}
  selector:
    matchLabels:
      app: {{ .Values.mongodb.spec.labels.app}}
  template:
    metadata:
      labels:
        app: {{ .Values.mongodb.spec.labels.app}}
    spec:
      containers:
      - name: {{ .Values.mongodb.spec.container_name}}
        image: {{ .Values.mongodb.spec.image.name}}: {{ Values.mongodb.spec.image.tag}}
        ports:
        - containerPort: {{ .Values.mongodb.spec.containerPort}}