apiVersion: {{ .Values.mongodb.apiversion }}
kind: {{ .Values.mongodb.kind }}
metadata:
  name: {{ .Values.mongodb.name }}
  namespace: {{ .Values.mongodb.namespace }}
spec:
  replicas: {{ .Values.mongodb.spec.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.mongodb.spec.labels.app }}
  template:
    metadata:
      labels:
        app: {{ .Values.mongodb.spec.labels.app }}
    spec:
      containers:
      - name: {{ .Values.mongodb.spec.container_name }}
        image: {{ .Values.mongodb.spec.image.name }}: {{ Values.mongodb.spec.image.tag }}
        ports:
        - containerPort: {{ .Values.mongodb.spec.containerPort }}
        env:
        - name: {{ .Values.mongodb.spec.env.name }}
          valueFrom:
            configMapKeyRef:
              name: {{ .Values.mongodb.spec.env.config.name }}
              key: {{ .Values.mongodb.spec.env.name }}
        - name: {{ .Values.mongodb.spec.env.username }}
          valueFrom:
            configMapKeyRef:
              name:  {{ .Values.mongodb.spec.env.config.name }}
              key: {{ .Values.mongodb.spec.env.username }}
        - name: {{ .Values.mongodb.spec.env.key.username }}
          valueFrom:
            secretKeyRef:
              name: {{ .Values.mongodb.spec.env.key.name }}
              key: {{ .Values.mongodb.spec.env.key.username }}